language: node_js
node_js:
- 6

addons:
  postgresql: "9.4"
  apt:
    packages:
    - postgresql-9.4-plv8

services:
- postgresql

env:
  global:
    - PLV8_HOST: localhost
    - PLV8_USER: postgres
    - PLV8_DATABASE: postgres

notifications:
  email: false

deploy:
  provider: npm
  email: hello@langa.io
  api_key:
    secure: CXEIlbOJsRyow3/Khr8lVenL8/tO6iiiWvqR+pk+jQlc4sEPXSHdBFQAffnOeRbVEdbV1pSVYpctZsaUmAFiFpmcWFbNumkMfgT1Sg/Uq9LkBL/g4Rrz4cadwC/no2M+xpXccVH2/QgO5aqw8q5nj+rWjq3S/oflCmeKlwktr5fzhFpZzAN3YovqLBFkC2ItHTvjiv30ITpZQDhITzEqNV8K29hvk9mQDAjwm7Uns1vDRp8BoB42oYF8SFeJ44RJ0Px+cZ98WLvA0zb1bsOLNx0jnO9O0o5toFQkA+E63yWA3b7y6mq1pOd2WoVBuijk7lsaqrHIZnImkZbQsMEyNWT1xG98DV+M6C7b3GR4pO+hGtld+2a50h1sppDF1EkgokLu5bnKVIteMFAThb5dloHU2VT74XhIHzevyBvHo/XRIBJhT/2IZdHS8NVuF+B9aZ1sm0j/VWOJ8sFY9biQBIdAxLb1nH/vlCjhLodDD3tc6IXo3cXIULcOKTwjZZdplyoApGAtCFc6Ga6wD5aqaing3/DyV/nhJ7YG3HDeMAS0oYHxO83rgpPkQArE/l75qGs8j5VN7fcj1BCn66sHtEQ8IpbDwlnWW31YU4qPZe9UCqLYuJX27UoDNQViJbeQhgotTf38nK9cfT8xjxaWdYDMzzJiJHSNPnN/PjV5yRU=
  on:
    tags: true
    repo: langateam/plv8
    all_branches: true
    node: 6
