language: node_js
node_js:
- 6
- 7

addons:
  postgresql: '9.4'
  apt:
    packages:
    - postgresql-9.4-plv8

services:
- postgresql

env:
  global:
  - PLV8_HOST: localhost
  - PLV8_USER: postgres
  - PLV8_DATABASE: postgres

notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/54f8a1e753f859f5ca1a
    on_start: never
    on_failure: change

deploy:
  provider: npm
  email: hello@langa.io
  api_key:
    secure: xl//JGtfs97f4kqO5rKI6GQzbcbqupJoSxqfZaQTG7TQslWDAdM/jwbKU8kXgP8cO8fZ+K7OXue5cdbLVYMdByf8Tl3d3Zo8Z3EUEpsI4H/RinAiNQErngXtJAHM2wIOgQCQdeAylqneRhlVTYehByF55L4OEDUo8umYnKh0mzITWrWhjycn/kyhFbHznjgTQnvgsOBz6wjD7YlPpmMOq474Ldn22nIsTuVxyHilY3i899IPD1BczNMN56mkOcchEZJOchuv11eBeiuLajpTUH/jIkZi1OQSYQqaree5sqAvjGnSoX1EsdFXQexFSNYsYtV1Va1+opzdkGMUnJ7Tf0P4a0Lr+fP53hayXRhKCnKJAJhGW0kJ6UK8y7qpI383zc+FGqTHGeCkFWbAVX1tWmYTtFKuyW94i36O6UIlXPDERIhQbC3xm6ERd+xYCbnJsFgFseYKNH1q+e8XGHd/SwRDlkEDfpQ+DOEKYxbDZcLdil76aLkwGtdstuDx1D/2fz+JzRU0XD2vZXah2+ceOytk7C4oi4E6PrKFx5MoDnhcgWwtYDcEMTXzqoMLJPMxlOkF37ksj58lgdkhqNt8j2lWBsy8kBsrBhJCuMCzH7/MVmWYJ7B8fULcqmEmEXM9TvZfgyEuOa6R5lXhiCGkb8+QScLQu7IGIebRqURTTsc=
  on:
    tags: true
    repo: langateam/node-plv8
    node: 6
